networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "7001:80"
    volumes:
      - ./dockerize_laravel/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/html
    depends_on:
      - manage_students
    networks:
      - laravel

  manage_students:
    build:
      context: .
      dockerfile: dockerize_laravel/php/Dockerfile
    container_name: manageStudents
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - laravel
volumes:
  dbdata:
    driver: local
